name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - oscript_version: 'default'
            test_engine: '1testrunner'
          - oscript_version: 'lts-dev'
            test_engine: '1testrunner'
          - oscript_version: 'dev'
            test_engine: 'oneunit'
    uses: autumn-library/workflows/.github/workflows/test.yml@oneunit
    with:
      oscript_version: ${{ matrix.oscript_version }}
      test_engine: ${{ matrix.test_engine }}
